// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using librarymanagementsystem.DataAccessLib.Contexts;

#nullable disable

namespace DataAccessLib.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260518064543_UserModelColumnUpdate")]
    partial class UserModelColumnUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("librarymanagementsystem.ModelLib.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.BookCopies", b =>
                {
                    b.Property<int>("BookCopiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookCopiesId"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("DamageDescription")
                        .HasColumnType("text");

                    b.Property<int>("DamagePercentage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("BookCopiesId");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.BookReturnTransactions", b =>
                {
                    b.Property<int>("BookReturnTransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookReturnTransactionsId"));

                    b.Property<int>("BorrowTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionOnReturn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsHardCoverMissing")
                        .HasColumnType("boolean");

                    b.Property<int>("NoOfMissingPages")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookReturnTransactionsId");

                    b.HasIndex("BorrowTransactionId");

                    b.ToTable("BookReturnTransactions");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.BorrowTransactions", b =>
                {
                    b.Property<int>("BorrowTransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BorrowTransactionsId"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("BorrowTransactionsId");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowTransactions");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.FineTransactions", b =>
                {
                    b.Property<int>("FineTransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FineTransactionsId"));

                    b.Property<int>("BookReturnTransactionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FineTransactionsId");

                    b.HasIndex("BookReturnTransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("FineTransactions");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.MembershipTypes", b =>
                {
                    b.Property<int>("MembershipTypesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipTypesId"));

                    b.Property<int>("MaxBooksAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("MaxBorrowDays")
                        .HasColumnType("integer");

                    b.Property<string>("MembershipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MembershipTypesId");

                    b.ToTable("MembershipTypes");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.Rules", b =>
                {
                    b.Property<int>("RulesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RulesId"));

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("ruleDescription")
                        .HasColumnType("integer");

                    b.HasKey("RulesId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("BorrowedCopies")
                        .HasColumnType("integer");

                    b.Property<int>("DamagedCopies")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("integer");

                    b.HasKey("StockId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MemberRole")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipTypesId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("MembershipTypesId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.UserStat", b =>
                {
                    b.Property<int>("UserStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserStatId"));

                    b.Property<int>("BooksBorrowed")
                        .HasColumnType("integer");

                    b.Property<int>("BooksOverdue")
                        .HasColumnType("integer");

                    b.Property<int>("BooksReturned")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalFinesPaid")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalUnpaidFines")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserStatId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.BookCopies", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.BookReturnTransactions", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.BorrowTransactions", "BorrowTransaction")
                        .WithMany()
                        .HasForeignKey("BorrowTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowTransaction");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.BorrowTransactions", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.BookCopies", "BookCopy")
                        .WithMany()
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("librarymanagementsystem.ModelLib.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("librarymanagementsystem.ModelLib.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookCopy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.FineTransactions", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.BookReturnTransactions", "BookReturnTransaction")
                        .WithMany()
                        .HasForeignKey("BookReturnTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("librarymanagementsystem.ModelLib.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookReturnTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.Stock", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.Book", "Book")
                        .WithOne("Stock")
                        .HasForeignKey("librarymanagementsystem.ModelLib.Stock", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.User", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.MembershipTypes", "MembershipType")
                        .WithMany("Users")
                        .HasForeignKey("MembershipTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.UserStat", b =>
                {
                    b.HasOne("librarymanagementsystem.ModelLib.User", "User")
                        .WithOne("UserStat")
                        .HasForeignKey("librarymanagementsystem.ModelLib.UserStat", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.Book", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.MembershipTypes", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("librarymanagementsystem.ModelLib.User", b =>
                {
                    b.Navigation("UserStat");
                });
#pragma warning restore 612, 618
        }
    }
}
